language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer require --no-interaction --prefer-dist --dev php-coveralls/php-coveralls

script: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success: php vendor/bin/php-coveralls --verbose
